./a.out < dna/1_1.in
./a.out < dna/1_2.in
./a.out < dna/1_3.in
./a.out < dna/2_1.in
./a.out < dna/2_2.in
./a.out < dna/2_3.in
./a.out < dna/3_1.in
./a.out < dna/3_2.in
./a.out < dna/3_3.in
./a.out < dna/4_1.in
./a.out < dna/4_2.in
./a.out < dna/4_3.in
./a.out < dna/5_1.in
./a.out < dna/5_2.in
./a.out < dna/5_3.in
./a.out < dna/6_1.in
./a.out < dna/6_2.in
./a.out < dna/6_3.in
./a.out < dna/7_1.in
./a.out < dna/7_2.in
./a.out < dna/7_3.in
./a.out < dna/8_1.in
./a.out < dna/8_2.in
./a.out < dna/8_3.in
./a.out < dna/9_1.in
./a.out < dna/9_2.in
./a.out < dna/9_3.in
./a.out < dna/10_1.in
./a.out < dna/10_2.in
./a.out < dna/10_3.in
